# 🎵 Concert Tours Dataset — Data Cleaning Practice
**Dataset:** Top Grossing Concert Tours (Kaggle)

### Step 1 — Import Library & Load Dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

### Step 2 — Initial Inspection

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [4]:
df.to_string()

'    Rank   Peak All Time Peak     Actual\xa0gross Adjusted\xa0gross (in 2022 dollars)        Artist                                Tour title    Year(s)  Shows Average gross      Ref.\n0      1      1             2     $780,000,000                     $780,000,000  Taylor Swift                           The Eras Tour †  2023–2024     56   $13,928,571       [1]\n1      2      1          7[2]     $579,800,000                     $579,800,000       Beyoncé                    Renaissance World Tour       2023     56   $10,353,571       [3]\n2      3   1[4]          2[5]     $411,000,000                     $560,622,615       Madonna               Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294       [6]\n3      4   2[7]         10[7]     $397,300,000                     $454,751,555          Pink               Beautiful Trauma World Tour  2018–2019    156    $2,546,795       [7]\n4      5   2[4]           NaN     $345,675,146                     $402,844,849  Taylor Swift                   Reputation Stadium Tour       2018     53    $6,522,173       [8]\n5      6   2[4]         10[9]     $305,158,363                     $388,978,496       Madonna                             The MDNA Tour       2012     88    $3,467,709       [9]\n6      7  2[10]           NaN     $280,000,000                     $381,932,682   Celine Dion                 Taking Chances World Tour  2008–2009    131    $2,137,405      [11]\n7      7    NaN           NaN     $257,600,000                     $257,600,000          Pink                         Summer Carnival †  2023–2024     41    $6,282,927      [12]\n8      9    NaN           NaN     $256,084,556                     $312,258,401       Beyoncé                  The Formation World Tour       2016     49    $5,226,215      [13]\n9     10    NaN           NaN     $250,400,000                     $309,141,878  Taylor Swift                       The 1989 World Tour       2015     85    $2,945,882      [14]\n10    11    NaN           NaN  $229,100,000[b]                     $283,202,896       Beyoncé           The Mrs. Carter Show World Tour  2013–2014    132    $1,735,606  [15][16]\n11    12    NaN        14[17]     $227,400,000                     $295,301,479     Lady Gaga                   The Monster Ball Tour *  2009–2011    203    $1,118,227      [18]\n12    13    NaN           NaN     $204,000,000                     $251,856,802    Katy Perry                      Prismatic World Tour  2014–2015    151    $1,350,993      [19]\n13    14  1[20]           NaN     $200,000,000                     $299,676,265          Cher  Living Proof: The Farewell Tour ‡[21][a]  2002–2005    325      $615,385      [20]\n14    15   2[c]           NaN     $194,000,000                     $281,617,035       Madonna                          Confessions Tour       2006     60    $3,233,333       [5]\n15    16    NaN           NaN     $184,000,000                     $227,452,347          Pink                 The Truth About Love Tour  2013–2014    142    $1,295,775      [22]\n16    17    NaN           NaN     $170,000,000                     $213,568,571     Lady Gaga                        Born This Way Ball  2012–2013     98    $1,734,694       [d]\n17    18    NaN           NaN     $169,800,000                     $207,046,755       Madonna                          Rebel Heart Tour  2015–2016     82    $2,070,732       [4]\n18    19    NaN           NaN  $167,700,000[e]                     $204,486,106         Adele                           Adele Live 2016  2016–2017    121    $1,385,950      [25]\n19    20    NaN           NaN     $150,000,000                     $185,423,109  Taylor Swift                              The Red Tour  2013–2014     86    $1,744,186      [26]'

In [5]:
df.isnull().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [6]:
df.shape

(20, 11)

### Step 3 — Fix Column Names

In [8]:
df.columns.to_list()

['Rank',
 'Peak',
 'All Time Peak',
 'Actual\xa0gross',
 'Adjusted\xa0gross (in 2022 dollars)',
 'Artist',
 'Tour title',
 'Year(s)',
 'Shows',
 'Average gross',
 'Ref.']

In [9]:
df.columns = df.columns.str.replace("\xa0", " ", regex=False).str.strip()

In [10]:
df.columns.to_list()

['Rank',
 'Peak',
 'All Time Peak',
 'Actual gross',
 'Adjusted gross (in 2022 dollars)',
 'Artist',
 'Tour title',
 'Year(s)',
 'Shows',
 'Average gross',
 'Ref.']

### Step 4 — Drop Useless Column `Ref.`

In [11]:
df.drop(columns="Ref.", inplace=True)
print(df.columns.to_list())
print()
print(df.shape)

['Rank', 'Peak', 'All Time Peak', 'Actual gross', 'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)', 'Shows', 'Average gross']

(20, 10)

### Step 5 — Clean Money Columns 
#### `Actual gross, Average gross, Adjusted gross (in 2022 dollars)`

In [12]:
for col in ["Actual gross", "Average gross", "Adjusted gross (in 2022 dollars)"]:
    df[col] = df[col].str.replace(r"[^0-9]", "", regex=True).astype(int)

print(df[["Actual gross", "Average gross", "Adjusted gross (in 2022 dollars)"]].dtypes)
print(df[["Actual gross", "Average gross", "Adjusted gross (in 2022 dollars)"]].head())

Actual gross                        int32
Average gross                       int32
Adjusted gross (in 2022 dollars)    int32
dtype: object
   Actual gross  Average gross  Adjusted gross (in 2022 dollars)
0     780000000       13928571                         780000000
1     579800000       10353571                         579800000
2     411000000        4835294                         560622615
3     397300000        2546795                         454751555
4     345675146        6522173                         402844849

### Step 6 — Clean `Peak` & `All Time Peak` Columns

In [21]:
df["Peak"] = df["Peak"].str.replace(r"\[.*?\]", "", regex=True).str.strip()
df["All Time Peak"] = df["All Time Peak"].str.replace(r"\[.*?\]", "", regex=True).str.strip()

print(df[["Peak", "All Time Peak"]])

   Peak All Time Peak
0     1             2
1     1             7
2     1             2
3     2            10
4     2           NaN
5     2            10
6     2           NaN
7   NaN           NaN
8   NaN           NaN
9   NaN           NaN
10  NaN           NaN
11  NaN            14
12  NaN           NaN
13    1           NaN
14    2           NaN
15  NaN           NaN
16  NaN           NaN
17  NaN           NaN
18  NaN           NaN
19  NaN           NaN

### Step 7 — Clean `Tour title` Column

In [20]:
df["Tour title"] = df["Tour title"].str.replace(r"\[.*?\]", "", regex=True)
df["Tour title"] = df["Tour title"].str.replace(r"[^a-zA-Z0-9\s\-&]", "", regex=True).str.strip()
df["Tour title"]

0                      The Eras Tour
1             Renaissance World Tour
2                Sticky & Sweet Tour
3        Beautiful Trauma World Tour
4            Reputation Stadium Tour
5                      The MDNA Tour
6          Taking Chances World Tour
7                    Summer Carnival
8           The Formation World Tour
9                The 1989 World Tour
10    The Mrs Carter Show World Tour
11             The Monster Ball Tour
12              Prismatic World Tour
13    Living Proof The Farewell Tour
14                  Confessions Tour
15         The Truth About Love Tour
16                Born This Way Ball
17                  Rebel Heart Tour
18                   Adele Live 2016
19                      The Red Tour
Name: Tour title, dtype: object

### Step 8 — Clean `Year(s)` Column

In [24]:
df["Year(s)"] = df["Year(s)"].str.extract(r"(\d{4})").astype(int)
df["Year(s)"]

0     2023
1     2023
2     2008
3     2018
4     2018
5     2012
6     2008
7     2023
8     2016
9     2015
10    2013
11    2009
12    2014
13    2002
14    2006
15    2013
16    2012
17    2015
18    2016
19    2013
Name: Year(s), dtype: int32

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     int32
 4   Adjusted gross (in 2022 dollars)  20 non-null     int32
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     int32
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     int32
dtypes: int32(4), int64(2), object(4)
memory usage: 1.4+ KB

In [26]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour,2023,56,13928571
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour,2008,85,4835294
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018,156,2546795
4,5,2,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173