In [2]:
import numpy as np
import pandas as pd

In [5]:
data = {
    "Name": ["Ram", "Mohan", "Sonu", "Bhola"],
    "Age": [20, 23, 21, 22],
    "City": ["Raipur", "Bhilai", "Jaipur", "Rishikesh"],
    "Salary": [65000, 70000,  62000, 85000]
}

df = pd.DataFrame(data)
print(df)

    Name  Age       City  Salary
0    Ram   20     Raipur   65000
1  Mohan   23     Bhilai   70000
2   Sonu   21     Jaipur   62000
3  Bhola   22  Rishikesh   85000

In [11]:
data_list = [
    ["Ram",   20,     "Raipur",   65000],
    ["Mohan" ,  23 ,    "Bhilai" ,  70000],
    ["Sonu" ,  21 ,    "Jaipur" ,  62000],
    ["Bhola" ,  22,  "Rishikesh",   85000],
]
df2 = pd.DataFrame(data_list)
head_col = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list, columns= head_col)
df2

    Name  Age       City  Salary
0    Ram   20     Raipur   65000
1  Mohan   23     Bhilai   70000
2   Sonu   21     Jaipur   62000
3  Bhola   22  Rishikesh   85000

In [18]:
df2[["Name","Salary"]]

    Name  Salary
0    Ram   65000
1  Mohan   70000
2   Sonu   62000
3  Bhola   85000

In [19]:
df2["Designation"] = ["Doctor", "Engineer", "CEO", "HR"]

In [20]:
df2

    Name  Age       City  Salary Designation
0    Ram   20     Raipur   65000      Doctor
1  Mohan   23     Bhilai   70000    Engineer
2   Sonu   21     Jaipur   62000         CEO
3  Bhola   22  Rishikesh   85000          HR

In [23]:
df2.drop("Designation", axis=1)

    Name  Age       City  Salary
0    Ram   20     Raipur   65000
1  Mohan   23     Bhilai   70000
2   Sonu   21     Jaipur   62000
3  Bhola   22  Rishikesh   85000

In [24]:
df2

    Name  Age       City  Salary Designation
0    Ram   20     Raipur   65000      Doctor
1  Mohan   23     Bhilai   70000    Engineer
2   Sonu   21     Jaipur   62000         CEO
3  Bhola   22  Rishikesh   85000          HR

In [29]:
df2.drop([0,2], axis=0)

    Name  Age       City  Salary
1  Mohan   23     Bhilai   70000
3  Bhola   22  Rishikesh   85000

In [26]:
df2

    Name  Age       City  Salary
0    Ram   20     Raipur   65000
1  Mohan   23     Bhilai   70000
2   Sonu   21     Jaipur   62000
3  Bhola   22  Rishikesh   85000

In [36]:
df2.iloc[[2,0]]

   Name  Age    City  Salary
2  Sonu   21  Jaipur   62000
0   Ram   20  Raipur   65000

In [38]:
df.loc[[0,1]][["City", "Salary"]]

     City  Salary
0  Raipur   65000
1  Bhilai   70000

In [39]:
df.loc[[2,3]][["Name", "Age"]]

    Name  Age
2   Sonu   21
3  Bhola   22

In [40]:
df2

    Name  Age       City  Salary
0    Ram   20     Raipur   65000
1  Mohan   23     Bhilai   70000
2   Sonu   21     Jaipur   62000
3  Bhola   22  Rishikesh   85000

In [41]:
df2[df2["Age"] > 21]

    Name  Age       City  Salary
1  Mohan   23     Bhilai   70000
3  Bhola   22  Rishikesh   85000

In [47]:
df2[(df2["Age"]>21) & (df2["City"] == "Rishikesh")]

    Name  Age       City  Salary
3  Bhola   22  Rishikesh   85000