In [1]:
import numpy as np
import pandas as pd

In [2]:
data =  {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data=data)
df["Month"] = df["Date"].dt.month_name()
df["Quarter"] = "Q" + df["Date"].dt.quarter.astype("str")
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    474     74   John  January      Q1
1  2023-01-02       B   West    811     76   Mary  January      Q1
2  2023-01-03       C  North    386     38    Bob  January      Q1
3  2023-01-04       D  South    457     94  Alice  January      Q1
4  2023-01-05       A   East    112     34   John  January      Q1
5  2023-01-06       B   West    303     58   Mary  January      Q1
6  2023-01-07       C  North    904     58    Bob  January      Q1
7  2023-01-08       D  South    853     90  Alice  January      Q1
8  2023-01-09       A   East    875     64   John  January      Q1
9  2023-01-10       B   West    440     20   Mary  January      Q1
10 2023-01-11       C  North    755     92    Bob  January      Q1
11 2023-01-12       D  South    474     67  Alice  January      Q1
12 2023-01-13       A   East    408     21   John  January      Q1
13 2023-01-14       B   West    504     63   Mary  January      Q1
14 2023-01-15       C  North    967     55    Bob  January      Q1
15 2023-01-16       D  South    944     58  Alice  January      Q1
16 2023-01-17       A   East    316     82   John  January      Q1
17 2023-01-18       B   West    337     19   Mary  January      Q1
18 2023-01-19       C  North    516     35    Bob  January      Q1
19 2023-01-20       D  South    540     68  Alice  January      Q1

In [ ]:

pivot1 = pd.pivot_table(df, values="Sales", index="Region", columns="Product", aggfunc="median")

Product      A      B      C      D
Region
East     408.0    NaN    NaN    NaN
North      NaN    NaN  755.0    NaN
South      NaN    NaN    NaN  540.0
West       NaN  440.0    NaN    NaN

In [7]:
pivot2 = pd.pivot_table(df, values=["Sales", "Units"], index="Region", columns="Product")
# the dtype should be numeric 👇🏻
# pivot2 = pd.pivot_table(df, values=["Sales", "Quarter"], index="Region", columns="Product")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     437.0    NaN    NaN    NaN  55.0   NaN   NaN   NaN
North      NaN    NaN  705.6    NaN   NaN   NaN  55.6   NaN
South      NaN    NaN    NaN  653.6   NaN   NaN   NaN  75.4
West       NaN  479.0    NaN    NaN   NaN  47.2   NaN   NaN

In [8]:
pd.crosstab(df["Region"], df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [25]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [11]:
df1.shape

(5, 3)

In [12]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [16]:
print(df1)
df1.describe()

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [18]:
df1["A"] +10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [19]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [20]:
def sqaure(x):
    return x**2

sqaure(df1["B"])

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [26]:
df1["D"] = df1["B"].apply(sqaure)

In [27]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500